### ISSUE TITLE
Training DeepChem Models in Eager Mode

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1171]
Following discussion in #1158, it's looking like it will take a good bit more effort to train DeepChem models in Eager mode. Let's use this issue to coordinate discussion of the steps we need to take.

https://github.com/tensorflow/models/blob/master/official/mnist/mnist_eager.py provides an example of training an MNIST eager model. The model itself is defined in https://github.com/tensorflow/models/blob/master/official/mnist/mnist.py and looks to be a subclass of `tf.keras.Model`.

Is it possible to train our existing model objects directly in Eager mode or will we need to make them inherit `tf.keras.Model`?

**Comment by peastman** [comment]
Take a look at https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/base.py and search for occurrences of "eager".  You'll find first that the Tensorflow layer classes have a lot of code specifically to deal with eager mode, and second that a lot of that code is to throw exceptions when people try to use features that aren't currently supported!

Anyway, Tensorflow layers work a bit differently from TensorGraph ones.  In Tensorflow, `build()` constructs the variables and then `call()` creates the tensors to do the calculation (or in eager mode, just does the calculation).  TensorGraph combines both of those into a single method, so you can't perform the calculation without also recreating the variables.  We would need to split those apart.

**Comment by rbharath** [comment]
Good analysis!

I think it would be worth it for us to split the TensorGraph method apart so we can do variable construction and tensor creation separately. Probably better to bring our codebase to more closely match emerging tensorflow standards.

**Comment by peastman** [comment]
Let's think about how that can work.  It somewhat interacts with two features we already have, and might replace them.

`create_tensor()` has a `set_tensors` argument.  Usually that's `True`, which means to operate in the normal way.  That's how it's called by `TensorGraph.build()`.  It constructs all variables and tensors and sets the layer's `out_tensor` field.  If it's `False`, it basically does the same thing except that it doesn't change `out_tensor`.  It creates new variables and tensors, then returns the output tensor without altering the layer itself.  Do we actually use that feature for anything right now?  The only place I could find is in `make_estimator()`.

The other feature is `Layer.shared()`, which creates a new layer but makes that new layer share variables with the old one.  In the architecture used by Tensorflow and Keras, that's equivalent to just having a single layer, but including it at multiple places in the graph.

Anyway, there are various ways we could approach this.  One option is just to keep all current features working exactly as they do now.  When `create_tensor()` is called, it would check to see if it was in eager mode.  If not, it would do everything exactly as it currently does.  But in eager mode, it would switch to a different implementation that creates the variables only the first time it's called, stores them in the layer, and then does the calculation.

Alternatively we could change either or both of the above behaviors.  The `set_tensors=False` option especially doesn't seem to be used much, and it means something a bit like, though not quite the same as, calling the layer in eager mode.

**Comment by rbharath** [comment]
I think the `out_tensor=False` case was originally added with Eager in mind :). I think we'd be fine to change that behavior. I think `Layer.shared()` does see some usage though, so we might want to preserve it's present behavior.

I'm still trying to gauge how much code we'll have to change. As you point out, the TensorFlow team looks like they had to change a lot of their layers to make Eager work, so some churn might be unavoidable. Adding a flag check for Eager mode to existing layers might be the most straightforward implementation.

**Comment by peastman** [comment]
Here's a more detailed proposal.  If this sounds reasonable, I can get started on implementing it.

`create_tensor()` can be called in three modes:

1. `set_tensors=True`.  This is how it gets called by `TensorGraph.build()`.  Eager execution must not be enabled.  Specifying `set_tensors=True` in eager mode is an error and should produce an exception.  `in_layers` must *not* be specified.  `create_tensor()` creates all variables and tensors required by the layer and sets the `out_tensor` field.  It may only be invoked once on any layer in this mode.  Calling it twice in this mode is an error and should produce an exception.

2. `set_tensors=False`, eager mode disabled.  This is how it gets called by `TensorGraph.make_estimator()`.  `in_layers` *must* be specified.  `create_tensor()` creates all variables and tensors required by the layer, then returns the output tensor without modifying the layer.  It may be called any number of times in this mode.

3. `set_tensors=False`, eager mode enabled.  `in_layers` *must* be specified.  The layer's constructor (instead of `create_tensor()`) creates the variables and stores them in fields of the layer.  `create_tensor()` performs the calculations to compute the output tensor and returns it.

This assumes you will be working exclusively in graph mode, or exclusively in eager mode, but never try to combine them.  It has to be set before you create the layer, since the constructor behaves differently in the two modes.  This is consistent with the documentation on [`enable_eager_execution()`](https://www.tensorflow.org/api_docs/python/tf/contrib/eager/enable_eager_execution), which has the warning, "If not called immediately on startup risks creating breakage and bugs."

We could potentially get rid of the `set_tensors` flag, since it's redundant with the presence of the `in_layers` argument.

This will require changes to how we create and store variables.  I'll work that out as I go along.  We'll also likely need a lot of changes to TensorGraph to support using whole models in eager mode.  Loading and saving parameters will have to be done a bit differently, for example.  Training will also have to be done differently, or we might decide that `train()` only operates in standard mode.  You should be able to train a model in standard mode, write the parameters to a checkpoint, then (in a different Python session!) load those parameters and use them for prediction in eager mode.

**Comment by peastman** [comment]
Creating unit tests for this is going to be a problem.  `enable_eager_execution()` has to be called at the very start of the program, before doing anything at all with Tensorflow.  Once you've done anything else, even creating a single tensor, that Python session is committed to graph mode, and `enable_eager_execution()` will throw an exception.  Likewise, if you do call it at the very start, that Python session is committed to eager mode, and you can't do anything in graph mode from then on.

That means within a single run of `nosetests`, we can run tests for one mode or the other, but not for both.  We somehow need to completely divide all tests into two independent suites that get run separately.

Even for just running eager mode tests, I haven't figured out how to handle it cleanly.  When and where do we put the call to enable eager mode?  Calling `enable_eager_mode()` twice throws an exception, so we can't have each test do it.  And if you call `in_eager_mode()` to see if it's already been enabled, then it's too late.  Trying to enable it after that will fail because you've already done something else with Tensorflow.

**Comment by peastman** [comment]
Ok, digging through the Tensorflow source code I discovered they have a completely undocumented(!) mechanism to handle this.

```Python
from tensorflow.python.eager import context
with context.eager_mode():
  with tfe.IsolateTest():
    # Put test code here
```

And yes, you can actually have alternating blocks of `with context.eager_mode()` and `with context.graph_mode()`, and thus switch back and forth between the two modes.  I guess they don't want people actually doing that, since it could easily lead to bugs.  But how are you supposed to write tests without it?  So their compromise seems to have been to create a mechanism, and then leave it undocumented.  Sigh.

**Comment by rbharath** [comment]
Closing since implemented by #1191

**Comment by lilleswing** [comment]
PS Newer versions of tensorflow remove this mechanism and don't document how to solve the issue anymore :p

**Comment by lilleswing** [comment]
It has been replaced with this
https://www.tensorflow.org/api_docs/python/tf/contrib/eager/run_test_in_graph_and_eager_modes

**Comment by peastman** [comment]
That annotation existed before.  It just didn't work.  See https://github.com/tensorflow/tensorflow/issues/18055.

**Comment by lilleswing** [comment]
Yes -- and it wasn't really the problem with the tests.

It seems like
```python
context.eager_mode()
```
is sufficient for the tests we have.  However when I start the block twice within a single test it does not "clear" the existing ops or counters.

Newer versions don't allow mixing eager mode with placing ops on a Graph object.  We were using this mechanism for saving and loading.  We would place all the ops on a graph even in eager mode and then when it came time to save we would save the weights on the graph.  When it came time to load we would construct a new graph and place all the weights on that Graph.  

So now with the newer tensorflows saving/loading in eager mode is broken.  There are two options -- one is using eager execution in a graph environment described here
https://www.tensorflow.org/guide/eager

The other option is to somehow use restore_variables_on_create
https://www.tensorflow.org/api_docs/python/tf/contrib/eager/restore_variables_on_create.

Neither seem particularly easy right now.
