### ISSUE TITLE
What is the point in having GeneratorEvaluator?

### ISSUE THREAD

**Issue by simonfqy** [deepchem/deepchem#1172]
Hi, I was examining the code for `GraphConvTensorGraph` and found that it uses `GeneratorEvaluator`. It seems that `Evaluator` could do the job for `GraphConvTensorGraph`. What is the point of having a separate `evaluator` class which evaluates according to `generators`? Is it only for faster implementation (I assume) or are there other significances with the decision? Thanks.

**Comment by simonfqy** [comment]
It calls `TensorGraph.evaluate_generator()`, which in turn calls `GeneratorEvaluator`. You can see it here.
https://github.com/deepchem/deepchem/blob/2fbd119c44ffbb38234cc6bfbc6a96001d481c7d/deepchem/models/tensorgraph/models/graph_models.py#L862

And yes, I am asking the general usage. I don't know what is the necessity for having it in addition to `Evaluator` class.

**Comment by simonfqy** [comment]
@rbharath @lilleswing I hope that you answer this question. Besides, I found that in the following line, https://github.com/deepchem/deepchem/blob/0e21722f930af0380aa7392dcf22770ce22cb740/deepchem/models/tensorgraph/models/graph_models.py#L827 there is a comment saying: 

> GraphConvModel constantly outputs batch_size number of results, only valid samples should be appended to final results

I am not quite sure the validity of this sentence for `GraphConvModel`. Maybe the last batch of the epoch has a smaller size? I guess that maybe this setting is related to using `GeneratorEvaluator` class? Please correct me if I am wrong.

**Comment by rbharath** [comment]
It's possible that this could be refactored for simplicity but not sure. I'm unfortunately on mobile for the next couple days mainly so hard to do an in-depth read.

CC @peastman who might be able to help

**Comment by peastman** [comment]
I've never understood why `Evaluator` exists at all. :)  `fit()` and `predict()` are just implemented directly within the model.  I don't know why `evaluate()` is different, though I assume there's a reason.

**Comment by lilleswing** [comment]
Yes I agree that the current state of affairs for evaluation is pretty bad.  It is legacy code when we were going for more of a compositional approach vs an OO approach towards building models.  

It was compounded by the fact that at the time of writing that code we were worried about storing all the response variable in RAM and wanted to stream them.  We have since given up on this worry and frequently store all the response variables in RAM.

A new API to tensorgraph with evaluate(dataset, metric) which runs the prediction, stores the response in RAM and explicitly calls dataset.y, dataset.w would be a better approach then what we have now.

**Comment by rbharath** [comment]
Closing this old issue. Feel free to re-open if there are new things to add here.
