### ISSUE TITLE
import deepchem error

### ISSUE THREAD

**Issue by jananikrish92** [deepchem/deepchem#1206]
ImportError: numpy.core.multiarray failed to import error on ubuntu.
Is there a fix?

**Comment by abster12** [comment]
make a seperate environment for deepchem.This error is due to version mismatch of packages.

**Comment by jananikrish92** [comment]
I have installed in conda environment and yet i get the same error

**Comment by abster12** [comment]
Did you clone the repository and follow the instructions as given in the readme?

**Comment by abster12** [comment]
I am sorry but that seems to be a problem with your conda, Try recreating the environment and if that still gives a conda environment error you can try reinstalling anaconda or miniconda

**Comment by anusurendra** [comment]
@jananikrish92 @abster12 , I am having a similar problem. I installed deepchem using conda and have created a conda environment `conda create --name deepchemtest040518` and activated by `source activate deepchemtest040518`. However, when I run python and import deepchem `import deepchem as dc`. I get a module not found error. If I run pip list it seems that `deepchem (2.0.1.dev3186)` is present. Any help would be appreciated.

**Comment by peastman** [comment]
@anusurendra could you quote the full error message?  Is it not finding `deepchem`, or some other module that is indirectly used by it?

**Comment by anusurendra** [comment]
@peastman thanks for that. I have updated my question with the full error message.

**Comment by peastman** [comment]
Are you sure they're both referring to the same Python environment?  Try `which python` and `which pip`.

**Comment by anusurendra** [comment]
@peastman the output for `which python` is `/home/surendraa/anaconda3/envs/snowflakes040518/bin/python` and the `which pip` is `pip 9.0.3 from /home/surendraa/anaconda3/lib/python3.5/site-packages (python 3.5)`

**Comment by jananikrish92** [comment]
can deepchem be installed in windows?

**Comment by peastman** [comment]
I think we're discussing two different issues here.  The original one was an error importing numpy.  That's caused by having an out of date version of numpy installed.  Try `conda update numpy` and see if that fixes it.  If not, you may have something else installed that's pinning to the old version.  Try installing DeepChem in a clean environment.

The second issue is an error importing deepchem itself.  I'm not sure exactly what is happening there, but there clearly is something incorrect about the installation.  Just to make sure: after you created the environment with `conda create` and activated it with `source activate`, did you then (in the same terminal window) install DeepChem into that environment with `conda install`?

**Comment by rbharath** [comment]
Closing this issue since it's been inactive for a while. Feel free to re-open if necessary.
