### ISSUE TITLE
Text CNN issues

### ISSUE THREAD

**Issue by allchemist** [deepchem/deepchem#1223]
Hello, pls get some feedback about textcnn model:
* your chars dictionary is not full and misses some symbols, like '@'
* model.predict throws error if in test dataset there is a smiles char which was not presented in train set

**Comment by miaecle** [comment]
@allchemist Good catch! We only include the common characters in the default dict, to include other characters you need to call `build_char_dict`. For the second question, I think this makes some sense since if you meet with a totally unseen character in your testing even human will not be able to tell its meaning. The practical solution would be to combine `char_dict` separately built on train, valid and test. In general, `textcnn` model is pretty immature and if you have any suggestions or ideas on its potential improvement please feel free to open an specific issue or PR on the function you would like it to have.
