### ISSUE TITLE
Won't the trained model be saved? I want to create a model of GraphConv, then save it and load it for training, but I can't save the non - trained model?

### ISSUE THREAD

**Issue by zhouhao-learning** [deepchem/deepchem#1239]
This is the code I created the model
`model = GraphConvTensorGraph(len(tox21_tasks), batch_size=50, mode='classification',dropout=0.2,model_instance='keras',model_dir="/home/zh/0426")
model.save()`

But I got this mistake:
`Traceback (most recent call last):
  model.save()
session = self.session
AttributeError: 'GraphConvTensorGraph' object has no attribute 'session`

**Comment by lilleswing** [comment]
When you instantiate a TensorGraph class you are building a graph under the hood whenever you add layers to it.

The layers are only added to a tensorflow session when  you call TensorGraph.build() (fit and predict call build under the hood if it is not already "built").

Also since you have not fit anything here there is nothing to save!  All the weights are still in their initial state.  If you call fit or build on the model then it would be able to save.

**Comment by zhouhao-learning** [comment]
@lilleswing 
Hello, I didn't quite understand what you said last time. You said, I have to build on the model then it would be able to save. what do you say about it? Can it be specific?

**Comment by lilleswing** [comment]
So TensorGraph has a two stage model building process.

1) When you call 
```
#set_loss
#add_ouput
```
TensoGraph goes through all the layers attached to the loss and output and registers them internally in TensorGraph.layers

This means that TensorGraph has a Graph Definition for the computation you wish to perform.

2) When you actually want to do things with the Graph
this calls TensorGraph.build() under the hood.  This creates a a Tensorflow "Graph" object and places all the ops in the graph.  Actually putting the interally stored graph in the Tensorflow "Graph" object.  It also calls all the initializers.

Before this is done no model weights exist -- only the definition of what the weights will be exists.

A bug currently exists in the code where we can't save a model before TensorGraph.build() is called.  However there really is no purpose for this because no training has happened yet.  If you wish to save an initialized model without the weights you could just save the **kwargs you pass into the model instead.

**Comment by lilleswing** [comment]
This two step process is different when working in eager mode.

**Comment by rbharath** [comment]
Closing since it looks like issues have been worked out.
