### ISSUE TITLE
Failed to Reproduce Results for Weave

### ISSUE THREAD

**Issue by chao1224** [deepchem/deepchem#1258]
Hi, I am looking for the regenerating weave module results as reported in [https://arxiv.org/pdf/1603.00856.pdf](https://arxiv.org/pdf/1603.00856.pdf).

I loaded the hyperparameter as reported from MoleculeNet [http://deepchem.io.s3-website-us-west-1.amazonaws.com/trained_models/Hyperparameter_MoleculeNetv3.tar.gz,](http://deepchem.io.s3-website-us-west-1.amazonaws.com/trained_models/Hyperparameter_MoleculeNetv3.tar.gz,).

For example, when I was testing Delaney, I cannot reproduce RMSE in table 5 in first paper. But the pearson-r2 score is same as MoleculeNet.

**Comment by chao1224** [comment]
@miaecle Sure.  
Sorry I'm doing index splitting on delaney, and r2 is 0.872 instead of 0.756. 
r2 reported from [https://github.com/deepchem/deepchem/blob/1a7642604c09fb04c8bdbbc07abc574c812ec2db/devtools/jenkins/results.table](https://github.com/deepchem/deepchem/blob/1a7642604c09fb04c8bdbbc07abc574c812ec2db/devtools/jenkins/results.table)

| Eval | Re-run | Reported |
| :--- | --- | --- |
| r2 | 0.7616 | 0.872 |
|rmse | 0.99 | 0.46 |

I may try more epochs though.

**Comment by rbharath** [comment]
I'm rerunning the delaney weave and I'm getting the following results:

```
Train scores
{'mean-pearson_r2_score': 0.9426195023583721}
Validation scores
{'mean-pearson_r2_score': 0.8249890530217342}
```

This is somewhere between the runs reported here. I think there's a possibility this is issues with choice of random initializaiton of the model perhaps? I don't think there's an actual bug here but I could be mistaken. I'm going to close this issue, but please feel free to re-open if necessary.
