### ISSUE TITLE
Passing Transformer information between Datasets

### ISSUE THREAD

**Issue by joegomes** [deepchem/deepchem#143]
`Transformer` objects are re-initialized for every data set they operate on (e.g. train/test/validation).  Some `Transformers` (such as `CoulombBinarizationTransformer`) need to pass information from one instance (e.g. on train) to another (e.g. on test).  Currently this is causing a bug where on rare occasions `Dataset` objects have different data shapes.

One idea is to allow `transform` functions to return variables, although this idea would break every use of `Transformer` so not ideal.  Another idea is to have optional arguments for certain transformers to read/write data to disk.

**Comment by rbharath** [comment]
@joegomes Let's chat about this in person. IIRC, we initialize the `Transformer` objects only for train, and then re-use on test/validation..

**Comment by rbharath** [comment]
I get the issue after chatting IRL. The proposed fix is to add an `udate_state` flag to the `transform` method that indicates whether the `transformer` should update its internal state (say `self.X_mean` or `self.feature_max` based on this dataset). This flag should be set to `True` for `train_dataset` and false otherwise.

**Comment by joegomes** [comment]
Started a PR #144 to fix this issue for the `CoulombBinarizationTransformer` in particular
