### ISSUE TITLE
GraphConv Model and LIME

### ISSUE THREAD

**Issue by marcabrus** [deepchem/deepchem#1518]
- DeepChem Version: 2.1.1
- Platform: anaconda

Hi everyone, I'm new to deepchem. t seems a very good package expecially the integration with LIME.

I'm trying to use Graph convolutional models to extract relevant features and i was wondering if there is a way to use after the training the LIME explanation.
Is there also any tutorial that explains it?

**Comment by KacperKubara** [comment]
Hey marcabrus,
I have the same issue as you: I am trying to find explainability methods for GCNs. From what I understand LIME cannot be used with GCNs as it requires a fixed input size. The graph, especially molecules, usually vary in size so the input won't be fixed.

Having said so, I have found a few papers regarding explainability methods for GCNs. One of the methods to circumvent this problem is to generate fixed-size neural fingerprints using GCNs and then apply LIME. Another one might be to "convert" the standard CNN explanation methods to graph domain.

This field of research is quite new and there is v. small number of papers discussing this topic and I was not able to find their code implementation yet! If you are interested in these methods, have a look at the links below.

[http://openaccess.thecvf.com/content_CVPR_2019/papers/Pope_Explainability_Methods_for_Graph_Convolutional_Neural_Networks_CVPR_2019_paper.pdf](http://openaccess.thecvf.com/content_CVPR_2019/papers/Pope_Explainability_Methods_for_Graph_Convolutional_Neural_Networks_CVPR_2019_paper.pdf)

[http://papers.nips.cc/paper/5954-convolutional-networks-on-graphs-for-learning-molecular-fingerprints.pdf](http://papers.nips.cc/paper/5954-convolutional-networks-on-graphs-for-learning-molecular-fingerprints.pdf)

Best,
Kacper

**Comment by rbharath** [comment]
@KacperKubara Great links! Will check these out myself later...
