### ISSUE TITLE
What is predict_on_smiles_batch()?

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1590]
GraphConvModel has a method called `predict_on_smiles()`.  But it's implemented using a method called `predict_on_smiles_batch()` which doesn't exist.  There's no such method defined anywhere in the source tree.  https://github.com/deepchem/deepchem/blob/c43482fd5d15e3df84920d7f0c9fbc1e3847499e/deepchem/models/tensorgraph/models/graph_models.py#L774-L775

Is this an unfinished feature?  A leftover from something old?  Should we just get rid of that method?

**Comment by rbharath** [comment]
This method came about in an attempt to make the models easier to use for newcomers (so that it would be possible to make predictions directly on smiles). I think though that we decided to reverse course later and removed part of the original implementation and didn't do it cleanly. I'm personally in favor of just removing the `predict_on_smiles*` functions altogether. I think that would make the code cleaner.

**Comment by peastman** [comment]
Ok, I'll do that.

**Comment by peastman** [comment]
Fixed by #1594.
