### ISSUE TITLE
Optimizing loading datasets

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1855]
As part of my efforts to improve the speed of GraphConvModel, I've been profiling some of our example scripts.  I discovered that nearly half the time is actually spent loading shards, not in anything to do with the model.  I'd like to see if we can improve this.

One obvious solution is to cache shards in memory rather than reloading them every time.  DiskDataset is designed to let you work with datasets that are too big to fit in memory.  But in practice a lot of datasets are quite small and could easily fit in memory.  The challenge, though, is figuring out how much we can safely cache.  It's too bad Python doesn't support soft references, since they'd be perfect for this.  Any thoughts about this?

Digging a little deeper, I see that almost all the loading time is actually spent in numpy_pickle.py.  We store shards in `.joblib` files, which store data in pickled format.  Pickling is really slow.  Would it be possible to switch to `.npy` files instead?  I haven't tested yet, but I suspect that would be a lot faster.  What was the reason for choosing this format?

**Comment by peastman** [comment]
Based on some preliminary testing, loading a shard stored in a .npy file seems to be about 2-3 times faster than loading one stored in a .joblib file.

**Comment by vsomnath** [comment]
Do you think h5py provides a neat way to do soft referencing? - http://docs.h5py.org/en/stable/refs.html

**Comment by peastman** [comment]
I don't think that's the same thing.  That appears to be a way of referencing data stored in a file.  We want references to data in memory—we can always reload it if necessary.  The goal is to keep it in memory as long as possible and only garbage collect it if absolutely necessary.

**Comment by rbharath** [comment]
I'm not sure why we chose `joblib`. I think the reason might have been that the first version of the `DiskDataset` class used pickling directly and we swapped to `joblib` since it was more robust.

I think swapping to `.npy` files could be quite sensible for the speed improvements. If we can keep backwards compatible support for loading old `.joblib` files but move to `.npy` as the new default, this could be a pretty smooth transition. I'd be in favor of the shift if it helps speed up our models!
