### ISSUE TITLE
Failing tests for docking

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#1898]
I'm working on fixing the remaining slow tests that fail.  I found one I'm not sure what to do about: `test_pocket_vina_poses()`.  The failure is related to these lines:

https://github.com/deepchem/deepchem/blob/8edbeaa05431be3838d255bc9580d83d6ba04712/deepchem/dock/pose_generation.py#L216-L220

If `self.pocket_finder` is None then it writes out the `protein_pdbqt` file to disk.  But the else branch doesn't write it, so if you specified a pocket finder then it never writes that file.  However it still expects that file to exist a little later:

https://github.com/deepchem/deepchem/blob/8edbeaa05431be3838d255bc9580d83d6ba04712/deepchem/dock/pose_generation.py#L266-L273

What is the correct fix for this?

**Comment by rbharath** [comment]
Oh my apologies! I should have caught this in on my test cases. The correct fix is that these lines:

https://github.com/deepchem/deepchem/blob/8edbeaa05431be3838d255bc9580d83d6ba04712/deepchem/dock/pose_generation.py#L218-L220

Should be moved before the if/else so that the protein pdbqt is always written to disk. The binding pocket is simply used to tell autodock vina where on the protein it should try to dock.

**Comment by peastman** [comment]
Ok, thanks!

**Comment by peastman** [comment]
Fixed by #1902.
