### ISSUE TITLE
KerasModel.fit_on_batch is broken

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1909]
Here's a simple failing script

```
import deepchem as dc                                                  
import numpy as np                                                     
from rdkit import Chem                                                 
                                                                       
bi_tasks = ['a', 'b']                                                  
y = np.array([[1, 1]])                                                 
w = np.array([[1, 1]])                                                 
smiles = ['C']
mols = [Chem.MolFromSmiles(smile) for smile in smiles]                 
print("mols")                                                          
print(mols)
featurizer = dc.feat.ConvMolFeaturizer()                               
X = featurizer.featurize(mols)
# set up dummy new model first                                         
model = dc.models.GraphConvModel(n_tasks = len(bi_tasks),              
                                 graph_conv_layers = [128, 128],       
                                 dense_layer_size = 512,               
                                 dropout = 0,                          
                                 mode = 'regression',                  
                                 learning_rate = 0.001,                
                                 batch_size = 8,                       
                                 model_dir = "model")                  
model.fit_on_batch(X, y, w)
```

The error we see is 

```
Traceback (most recent call last):
  File "test_fit_on_batch.py", line 23, in <module>
    model.fit_on_batch(X, y, w)
  File "/Users/bharath/Code/deepchem/deepchem/models/keras_model.py", line 428, in fit_on_batch
    if not self.built:
AttributeError: 'GraphConvModel' object has no attribute 'built'
```

The bug is at this line https://github.com/deepchem/deepchem/blob/master/deepchem/models/keras_model.py#L428.

The issue is that neither `self.built` nor `self.build()` are available anymore. These need to be converted to use `self._ensure_built()` instead. We should also have a unit test for `fit_on_batch()` to avoid future errors.

**Comment by Ian-McCleary** [comment]
Hi there, I have run into a similar issue with GraphConvModel except it is for `batch_normalize`. Do you think this issue is related?
I know `batch_normalize` is listed as a parameter for GraphConvModel, however I get this error if I specify `batch_normalize=True/False` and if I don't specify it at all.  This is when I use the GridHyperparamOpt.

Using Deepchem docker 2.5.0

`params_dict = {
    'n_tasks': [task_count],
    'mode': ["regression"],
    'number_atom_features': [75, 100, 150],
    'graph_conv_layers': [[32, 32], [64,64]],
    'dense_layer_size': [64, 128],
    'dropouts': [0.2, 0.5],
    'learning_rate': [0.001]
}

optimizer = dc.hyper.GridHyperparamOpt(dc.models.GraphConvModel)
# Using NormalizationTransformer transform_y=True
best_model, best_hyperparams, all_results =  optimizer.hyperparam_search(params_dict, train_dataset, valid_dataset,
                                                                         metric, [transformer])                                                                  
print(all_results)
print("\n")
print(best_model)
print("\n")
print(best_hyperparams)

# Single evaluation model
print("Hyperparam list")
print(best_hyperparams[1])
print(best_hyperparams[2])


# supports width of channels from convolutional layers and dropout for each layer.
model = dc.models.GraphConvModel(
  n_tasks=task_count,
  number_atom_features=best_hyperparams[1],
  graph_conv_layers=best_hyperparams[2],
  dense_layer_size=best_hyperparams[3],
  dropouts=best_hyperparams[4],
  learning_rate=best_hyperparams[5],
  mode="regression"
)
`
Stack:
`Traceback (most recent call last):
  File "GraphConvMol.py", line 52, in <module>
    print(best_model)
  File "/miniconda/envs/deepchem/lib/python3.6/site-packages/sklearn/base.py", line 260, in __repr__
    repr_ = pp.pformat(self)
  File "/miniconda/envs/deepchem/lib/python3.6/pprint.py", line 144, in pformat
    self._format(object, sio, 0, 0, {}, 0)
  File "/miniconda/envs/deepchem/lib/python3.6/pprint.py", line 161, in _format
    rep = self._repr(object, context, level)
  File "/miniconda/envs/deepchem/lib/python3.6/pprint.py", line 393, in _repr
    self._depth, level)
  File "/miniconda/envs/deepchem/lib/python3.6/site-packages/sklearn/utils/_pprint.py", line 181, in format
    changed_only=self._changed_only)
  File "/miniconda/envs/deepchem/lib/python3.6/site-packages/sklearn/utils/_pprint.py", line 425, in _safe_repr
    params = _changed_params(object)
  File "/miniconda/envs/deepchem/lib/python3.6/site-packages/sklearn/utils/_pprint.py", line 91, in _changed_params
    params = estimator.get_params(deep=False)
  File "/miniconda/envs/deepchem/lib/python3.6/site-packages/sklearn/base.py", line 195, in get_params
    value = getattr(self, key)
AttributeError: 'GraphConvModel' object has no attribute 'batch_normalize'`
