### ISSUE TITLE
Parallelizing Transformers

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#1990]
At present the `Transformer` classes transform datasets as follows. Each `Transformer` defines a `transform_array(X, y, w)` method that transforms one batch of data. The full dataset is transformed by iterating over the dataset shards (for `DiskDataset`) and transforming one shard at a time.

This transformation technique should be easy to parallelize (although we might become IO bound with loading shards from disk perhaps). We should consider parallelizing Transformers. At present, transforming a large dataset is still quite slow.

CC @peastman

**Comment by peastman** [comment]
Good idea.  Currently `DiskDataset.transform()` works by creating a generator that loads each shard and transforms it.  Then it passes that generator to `create_dataset()`.

https://github.com/deepchem/deepchem/blob/3ce0aeebb7ec7fd03765fbcd4ce80b5de3712523/deepchem/data/datasets.py#L1346-L1353

`create_dataset()` iterates over the data provided by the generator and writes each shard to disk.

https://github.com/deepchem/deepchem/blob/3ce0aeebb7ec7fd03765fbcd4ce80b5de3712523/deepchem/data/datasets.py#L975-L979

Since Python doesn't let multiple threads run at the same time, we have to use multiple processes instead.  And we don't want to be passing lots of data back and forth between processes, because that's slow.  So we really want all the processing for each shard to be done in a single process: load the current shard, apply the transform, and write the new shard to disk.  It may take a little bit of rearchitecting to make that happen.

**Comment by peastman** [comment]
Do you have any examples where transforming is slow?  I think I have this working, but when I test on various examples I find that transforming never takes more than about a second to begin with, and only a tiny fraction of the time required to load and featurize the dataset.  And in most cases the parallel version is actually slower, because the overhead of spawning processes is greater than the very tiny benefit of doing the transforming in parallel.

**Comment by rbharath** [comment]
I have a large dataset I've been working with (around 50 GB) where I'm running `BalancingTransformer`. With the new `get_shard_w` method, it's reasonably fast, at 5-10 minutes or so I think (I can report exact numbers later). 

Unfortunately I can't share the above dataset, but a natural slow example might be an image dataset where we want to apply an image transformation. Perhaps as a synthetic benchmark, we could try loading MNIST and applying transformations to it?

**Comment by peastman** [comment]
I'll clean up my code and post a PR for it, then you can try it on your dataset and see how it affects performance.

**Comment by rbharath** [comment]
Thanks! Will do :)
