### ISSUE TITLE
How to learn deepchem?

### ISSUE THREAD

**Issue by icewaterice** [deepchem/deepchem#2078]
I would like to use deepchem, but I don't know how to start. And so manny questions confuse me,  there are lots of errors when I follow the tutorials to learn. Therefore I want to know, did deepchem has any useful doucement.   I appreciate to recieve a way to learn deepchem and your reply

**Comment by peastman** [comment]
Could you describe a bit about your background?  Are you already experienced in deep learning, and you just want to learn the specifics of DeepChem?  If so, the tutorials are the best place to start.  You need to use the correct version of DeepChem that each tutorial is written for.  That's a little complicated at the moment, because we're getting ready to release DeepChem 2.4 and we're in the process of updating the tutorials for it.  Checking out the latest code from the repository is probably best.

On the other hand, if you haven't done much with deep learning before, you'll first want to learn about the basics of that.  There are lots of good resources on the internet.  For example, this is a pretty good one: http://neuralnetworksanddeeplearning.com/

**Comment by icewaterice** [comment]
I am just a student, and know something of ML. And thanks you so much !
