### ISSUE TITLE
Failing to Train WGAN

### ISSUE THREAD

**Issue by alat-rights** [deepchem/deepchem#2247]
Hi everyone!

The following code is raising a dimension mismatch on the last line for me. I was wondering if anyone could help me approach fixing this? 

Error: `ValueError: Dimensions must be equal, but are 31 and 100 for '{{node functional_7/lambda_3/sub}} = Sub[T=DT_FLOAT](functional_7/gradient_penalty_layer_1/sequential_3/dense_11/Softplus, functional_7/sequential_3/dense_11/Softplus)' with input shapes: [31,1], [100,1].`

Here is a link to a minimal failing code sample: https://colab.research.google.com/drive/1bN_pxfox7CQGkBSQ1mCI9JAZ4mAK_E0I?usp=sharing#scrollTo=j2C88lZ_Dxyr

```Python
class BbbpGAN(dc.models.WGAN):

  def get_noise_input_shape(self):
    return (10,)

  def get_data_input_shapes(self):
    return [(1024,)]

  def create_generator(self):
    return tf.keras.Sequential([
        Dense(1024, activation=tf.nn.relu)
    ])

  def create_discriminator(self):
    return tf.keras.Sequential([
        Dense(1024, activation=tf.nn.relu),
        Dense(1, activation=tf.math.softplus)
    ])

gan = BbbpGAN(learning_rate=ExponentialDecay(0.001, 0.9, 5000))

def iterbatches(epochs):
  for i in range(epochs):
    for batch in train_dataset.iterbatches(batch_size=gan.batch_size):
      yield {gan.data_inputs[0]:batch[0]}
gan.fit_gan(iterbatches(100), generator_steps=0.2, checkpoint_interval=5000)
```

**Comment by peastman** [comment]
Try adding the argument `pad_batches=True` to the call to `train_dataset.iterbatches()`.  Does that fix it?

**Comment by alat-rights** [comment]
That fixed the problem, thank you very much! Would it be possible for you to explain how that works to me, if you have the time?

**Comment by peastman** [comment]
You told it to iterate in batches of 100 samples.  But what happens if your dataset isn't exactly a multiple of 100 samples?  It can either return a final smaller batch, or it can pad it out to the full size.  Your model expects all batches to be exactly the same size, so it gets an error if the final batch has a different size.

Actually, setting `pad_batches=True` may not be a good solution in this case.  It marks the extra samples used for padding by setting their weights to 0, which would normally cause them to be ignored.  But you're only passing in the features from the dataset, not the weights, so it will treat them as real samples.  It might be better to just ignore that batch.

You also can pass the number of epochs to `iterbatches()` rather than looping yourself.  Something like this:

```python
def iterbatches(epochs):
  for x, y, w, ids in train_dataset.iterbatches(batch_size=gan.batch_size, epochs=epochs):
    if len(ids) == gan.batch_size:
      yield {gan.data_inputs[0]:x}
```

**Comment by alat-rights** [comment]
Ah, I see! That's very helpful. Thank you.
