### ISSUE TITLE
setup.cfg having explicit and wrong version in release 2.3.0

### ISSUE THREAD

**Issue by fmonta** [deepchem/deepchem#2273]
Hello,
I encountered a problem when trying to pip install the version 2.3.0 as part of an environment. 
The setup.cfg of that particular version is still marked as 2.2.1. 
I had to pip install version 2.2.0 instead. You can read https://github.com/invl/retry/issues/8 to get an idea of the error message I was getting with v.2.3.0.

**Comment by rbharath** [comment]
@fmonta DeepChem 2.3.0 is very outdated. We're almost ready to release 2.4.0. In the meanwhile, could you upgrade to the nightly build? You can install this with `pip install --pre deepchem`

**Comment by fmonta** [comment]
I actually can't because I have other dependencies that require tensorflow 1.10... And since the readme mentions 2.3.0 as the current stable release I thought you might want to do this quick fix of the setup.cfg.

**Comment by nd-02110114** [comment]
> And since the readme mentions 2.3.0 as the current stable release I thought you might want to do this quick fix of the setup.cfg.

We don't support 2.3.0 version for pypi. Previously, DeepChem's support for pypi was somewhat immature due to the dependence on RDKit. So, our installation guide for stable version is **using conda** in README.

**Comment by fmonta** [comment]
Right, I saw you recommend using conda, and this actually works well. 
Just one thing, I am not trying to use pypi, I am using pip to install a particular version of the repo by doing `pip install git+https://github.com/deepchem/deepchem.git@2.3.0#egg=deepchem`(see [https://adamj.eu/tech/2019/03/11/pip-install-from-a-git-repository/](this) for an explanation of what I am doing). I believe the fix is really to change that one line in setup.cfg. Of course, feel free to close the issue if you don't think this will help other users.

**Comment by rbharath** [comment]
We definitely appreciate the error report!

The issue is rather that we're likely going to deprecate 2.3.0 support soon. The main reason is that the hosted MoleculeNet links from 2.3.0 are now broken (our old AWS infra run by Stanford was shut down recently and we've switched to new DeepChem AWS infrastructure with new URLs). 2.3.0 also depends on a number of old/outdated other packages, and it's not feasible for us to continue maintaining it given these issues. If it's at all feasible, we'd recommend upgrading to nightly. We're almost ready to release 2.4.0 which will be the next stable release
