### ISSUE TITLE
Mysterious Value-Error After Running WGAN Evaluate Function

### ISSUE THREAD

**Issue by alat-rights** [deepchem/deepchem#2282]
Hello team! <3

I'm trying to model the molnet Blood-Brain-Barrier-Penetion dataset with a WGAN. I'm getting a mysterious value-error when I run the Deepchem Model.evaluate() method. I was wondering if someone would help troubleshoot? 

Failing code sample on Colab (including training): https://colab.research.google.com/drive/1bN_pxfox7CQGkBSQ1mCI9JAZ4mAK_E0I#scrollTo=j2C88lZ_Dxyr

Error: 
```Compiler
ValueError: Input 0 of layer sequential_4 is incompatible with the layer: expected axis -1 of input shape to have value 10 but received input with shape [100, 1024]
```

Triggering code: 
```Python
metric = dc.metrics.Metric(
  dc.metrics.roc_auc_score, np.mean, mode="classification")

print("Evaluating model")
train_scores = gan.evaluate(train_dataset, [metric], transformers)
valid_scores = gan.evaluate(val_dataset, [metric], transformers)
test_scores = gan.evaluate(test_dataset, [metric], transformers)
```

**Comment by peastman** [comment]
I don't think `evaluate()` is meaningful for a GAN.  For ordinary models it sends in the features for each sample, gets the output, compares it to the corresponding label, and computes a metric based on how well they match.  That doesn't have any connection to how a GAN works: it doesn't even use the labels from the dataset.

It would be interesting to look into whether there's a generic method we could implement for evaluating a GAN.  It's a much more challenging problem than standard models, since there are so many aspects of its performance you might care about.  How well do generated samples resemble real samples?  How well does their distribution match the distribution of the training data?  How good is the discriminator at identifying generated samples?

**Comment by alat-rights** [comment]
Ah yikes... Thanks for the help Peter! 

I really need to figure out a way to compare performance between WGANs and standard models. 

Could you help me understand why exactly is it not be possible for a WGAN to make predictions on a separate test dataset in the same way any other model would?

**Comment by peastman** [comment]
A standard model is a function.  It takes inputs and produces outputs.  For example, take a photograph and determine whether it contains a cat.  For every input there is a definite correct answer.  For all the samples in your test set, you know what that correct answer is.  You can check the model's outputs when given those samples and see how accurate its predictions are.

A generative model is different.  The input is just random noise, and there's no unique "correct" output for any input.  You want to evaluate whether the outputs match the same distribution you trained the model on.  Do the outputs look convincingly like cats?  That isn't something you can determine just by comparing an output to a label.  And even if the individual outputs are good, the distribution may be wrong.  Perhaps the training data contained cats of many different breeds in different positions.  The outputs look convincingly like cats, but all of them are gray short haired cats viewed from the side.  Any individual output looks reasonable, but the distribution of outputs doesn't match the distribution of the training data.

That's why generative models are much more complicated to evaluate.

**Comment by alat-rights** [comment]
I see, thank you! I'll raise a new issue on possible Deepchem implementations of evalutors for GANs in the near future :)
