### ISSUE TITLE
Weave featurizer does not work with torch model

### ISSUE THREAD

**Issue by ujvl** [deepchem/deepchem#2361]
## 🐛 Bug

Using `featurizer="Weave"` results in the below error when trying to train `dc.models.torch_models.MPNNModel`. The same code works if I replace the featurizer with `MolGraphConvFeaturizer` or if I use the tf model implementation instead.

## To Reproduce

Run:
```
_, delaney_datasets, transformers = dc.molnet.load_delaney(featurizer="Weave")
train_dataset, valid_dataset, test_dataset = delaney_datasets
model = dc.models.torch_models.MPNNModel(
    mode='regression',
    n_tasks=1,
    number_atom_features=75,
    number_bond_features=14,
    node_out_feats=2,
    edge_hidden_feats=2,
    num_step_message_passing=1,
    num_step_set2set=1,
    num_layer_set2set=1)
model.fit(train_dataset, nb_epoch=1)
```

Stacktrace:
```
Traceback (most recent call last):
  File "deepchem/models/torch_models/torch_model.py", line 286, in fit
    checkpoint_interval, restore, variables, loss, callbacks, all_losses)
  File "deepchem/models/torch_models/torch_model.py", line 363, in fit_generator
    inputs, labels, weights = self._prepare_batch(batch)
  File "deepchem/models/torch_models/mpnn.py", line 303, in _prepare_batch
    graph.to_dgl_graph(self_loop=self._self_loop) for graph in inputs[0]
  File "deepchem/models/torch_models/mpnn.py", line 303, in <listcomp>
    graph.to_dgl_graph(self_loop=self._self_loop) for graph in inputs[0]
AttributeError: 'WeaveMol' object has no attribute 'to_dgl_graph'
```

## Environment

OS: Ubuntu
Python version: 3.6
DeepChem version: 2.4.0-rc1.dev
RDKit version (optional): 2020.09.1
TensorFlow version (optional): 1.6.0
TensorFlow version (optional): 2.3.0

**Comment by peastman** [comment]
The weave featurizer is specific to the weave model.  It isn't meant to work with arbitrary models.

**Comment by ujvl** [comment]
It looks like there are quite a few examples in this repo using the weave featurizer w/ MPNN though: 

- in tests: https://github.com/deepchem/deepchem/blob/master/deepchem/models/tests/test_graph_models.py#L230-L296
- in examples: https://github.com/deepchem/deepchem/blob/master/examples/delaney/delaney_MPNN.py

^ these seem to work with the tf implementation, but not the pytorch one.

**Comment by rbharath** [comment]
Good point that the documentation/examples are a little confusing here! Longer term, our plan is to switch over to using `MolGraphConvFeaturizer` as a common featurizer for all the graph based methods, but right now we have a bit of a confusing mix of different featurizations for different graph models. The right fix here is to probably make it so that `WeaveModel` accepts `MolGraphConvFeaturizer` rather than the other way around. I'll mark this issue as contribution welcome

CC @nd-02110114 who has been working on unifying our featurizer representation

**Comment by sumenties** [comment]
@rbharath can't we modify the deepchem featurizers for our own GNN architectures built using PyTorch geometric? In the end, we just want node/edge features with edge indices. I'm asking this because MolGraphConvFeaturizer has only 30 node features per atom. So are there any hard-bound rules/restrictions if we can use deepchem features beyond deepchem-based GNN models?
