### ISSUE TITLE
Listing Known Issues & Limitations

### ISSUE THREAD

**Issue by alat-rights** [deepchem/deepchem#2376]
Hi everyone!

I'm currently working on creating a list of known issues, untested modules, and problematic modules for the Deepchem documentation. 

Please let me know if you know of areas of Deepchem with known issues!

@rbharath @peastman

**Comment by rbharath** [comment]
Thanks for getting this started! A few that come to mind off top of head:

- `AtomicConvModel` is broken right now
- `RdkitGridFeaturizer` is broken right now
- Mol2 loading isn't well tested
- Interaction fingerprints more broadly need additional testing.
- The ANIFeaturizer/ANIModel are broken and probably should be removed since `TorchANI` is available

Other folks should chime in here too. CC @nd-02110114 @ncfrey @seyonechithrananda
