### ISSUE TITLE
Google Colab RDKit ImportError

### ISSUE THREAD

**Issue by ThiagoReschutzegger** [deepchem/deepchem#2413]
## 🐛 Bug

While trying to import the RDKit package with `from rdkit import Chem`, an unexpected error was thrown. I have run the same code before and never got this error. Some tutorials provided by DeepChem present the same error.

## To Reproduce

1. Run the standard DeepChem header
2. Import DeepChem
3. Import RDKit

```
/root/miniconda/lib/python3.7/site-packages/rdkit/DataStructs/__init__.py in <module>()
     11 
     12 from rdkit import rdBase
---> 13 from rdkit.DataStructs import cDataStructs
     14 from rdkit.DataStructs.cDataStructs import *
     15 

ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /root/miniconda/lib/python3.7/site-packages/rdkit/DataStructs/cDataStructs.so)
```

## Expected behavior

Should import the RDKit package

## Environment

* OS: - 
* Python version: - 
* DeepChem version: 2.5.0.dev
* RDKit version (optional): - 
* TensorFlow version (optional): - 
* PyTorch version (optional): - 
* Any other relevant information: -

**Comment by rbharath** [comment]
We have a workaround at https://github.com/deepchem/deepchem/issues/2411 that might fix the immediate error, but we should get a more robust fix in place.

@nd-02110114 Would you have any suggestions for how we could fix the underlying issue? Perhaps we should just pin an older version of RDKit for now

**Comment by nd-02110114** [comment]
> Would you have any suggestions for how we could fix the underlying issue? Perhaps we should just pin an older version of RDKit for now

I have no idea for fixing the underlying issue... This issue is related to C++ dependencies, so I think the only thing we can do is pin an older version of RDKit.

According to [this stackoverflow](https://stackoverflow.com/questions/65487584/how-to-import-rdkit-in-google-colab-these-days), we can avoid this error with the latest RDKit by running the following commands and restarting the notebook. But, it is difficult to automate the restarting the notebooks using the install script.

```bash
!add-apt-repository ppa:ubuntu-toolchain-r/test
!apt-get update --fix-missing
!apt-get dist-upgrade
```
