### ISSUE TITLE
Upgrading to Pytorch 1.8.1

### ISSUE THREAD

**Issue by VIGNESHinZONE** [deepchem/deepchem#2517]
Deepchem is currently using Pytroch 1.6.0

There has been a new error in github actions- 
```
>     torch.maximum(1 - torch.multiply(labels, output), torch.tensor(0)), 2), dim=-1)
E     AttributeError: module 'torch' has no attribute 'maximum'

```
And problem is that the `maximum` method was only introduced in [Pytorch #42579](https://github.com/pytorch/pytorch/pull/42579).

There is just one problem in Upgrading to Pytorch > 1.8, they support only Cuda 10.2 onwards, as mentioned [here](https://pytorch.org/get-started/locally/)

@rbharath so I think we should also start thinking about upgrading Cuda as well.

Here Momentary fixes to solve this issue before Deepchem's upcoming release- 
1) Either we change the `maximum` method? ----> Works well in PR #2508 
2) Or we need to be using Pytorch 1.7 which supports Cuda 10.1 ----> Creating Segmentation fault PR #2518

**Comment by VIGNESHinZONE** [comment]
The error can be ignored as I have fixed it, but we still need to plan for upgrading Cuda and Pytorch

**Comment by rbharath** [comment]
Thanks for the fixes! The segmentation fault for upgrading to PyTorch 1.7 is really confusing to me. One possibility is that TF 2.4 requires CUDA 11 which maybe is causing a mismatch? Perhaps we should just jump upgrade to the latest pytorch 1.8.1 as you suggest since we already require CUDA 11 due to the TF 2.4.x usage
