### ISSUE TITLE
Make TensorFlow optional

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#2561]
Now that TensorFlow is only one of several frameworks we use, we should make it an optional dependency.  Currently if you don't have TensorFlow installed, `import deepchem` will fail.  We should put the imports for TF based features inside try/except blocks or only `import tensorflow` inside functions, the same way we do for PyTorch.

**Comment by rbharath** [comment]
This is definitely something we should do!

**Comment by VIGNESHinZONE** [comment]
During my time working on setting `deepchem-jax`, I had tried debugging this problem becuase I wasnt able to execute a simple `import deepchem` without installing `tensorflow`. Deepchem also has a torch dependency, but it has tackled torch dependency by using 

https://github.com/deepchem/deepchem/blob/595d13b25877fe2a678f22d15d8171c0f431420f/deepchem/models/__init__.py#L29-L31

Here are the sub packages with hard dependencies in Tensorflow - `metalearning`, `keras_models`, `rl`. Even `trans` subpackage has a hard dependency on `TensorFlow` but can be fixed with simple `imports` inside classes & functions.

I had tried `try` & `catch` blocks on those above-mentioned sub-packages in this commit- https://github.com/VIGNESHinZONE/deepchem/commit/6f065998c46a4cb822d5a56eb467dc2b58c9d6ed

Later decided to remove, because it was making slightly huge design changes.
