### ISSUE TITLE
Standard API for retrieving model parameters

### ISSUE THREAD

**Issue by peastman** [deepchem/deepchem#2562]
Currently there is no uniform API to retrieve the parameters of a model.  On a TorchModel you can call `model.model.parameters()`, which returns a generator that produces PyTorch tensors.  On a KerasModel you can access `model.model.trainable_variables` which contains a list TensorFlow Variable objects.  For a SklearnModel there's probably also some way of doing it, though I'm not sure what it is.

We should consider creating a standard API to retrieve the parameters of any model in a uniform format.

**Comment by rbharath** [comment]
A standard API would be very useful and would smooth our way towards a ModelHub (https://forum.deepchem.io/t/a-sketch-of-a-modelhub/445) since it would give us a model-agnostic way of getting the parameters of a model.

A model-agnostic way of setting parameters would be very useful as well but likely harder to implement

**Comment by rbharath** [comment]
Given we are standardizing toward torch models, I think we can just recommend `model.model.parameters()` for now (although that doesn't resolve the question for sklearn/gbm). Going to close for now since we don't have plans to work on this at present but may possibly reopen later
