### ISSUE TITLE
GaussianHyperParameter failing test

### ISSUE THREAD

**Issue by vsomnath** [deepchem/deepchem#2615]
## 🐛 Bug

The `TestGaussianHyperparamOpt.test_rf_example_min` test is constantly failing. Just raising this issue to have it tracked

## Expected behavior

The test should not fail. In the image below, the minimum value should be -0.029 but for some reason, this is missing from `all_results`. 
![image](https://user-images.githubusercontent.com/32259379/126771448-eaebfbea-98ea-4dec-87d8-4ba6ce3d3938.png)

Is this a known issue? I will take a crack at this later.

**Comment by peastman** [comment]
It's one of the ones documented in #2588.  I've been debugging it in #2619.

I partly understand what's going on.  You can see the problem from the output:

```
Evaluation 	 Proposed point 	  Current eval. 	 Best eval.
init   	 [20.]. 	  -0.012048891829999086 	 -0.012048891829999086
init   	 [31.]. 	  -0.024255922987357136 	 -0.012048891829999086
init   	 [20.]. 	  -0.02963311794236168 	 -0.012048891829999086
1      	 [2.]. 	  -0.15577871804642351 	 -0.012048891829999086
2      	 [39.]. 	  -0.04449672719564744 	 -0.012048891829999086
```

Notice that pyGPGO is calling `optimizing_function()` twice with exactly the same value of the hyperparameter (n_estimators=20).  I don't know why it would do that.  At best it seems wasteful.  But in our case, the function is not deterministic.  If you train two models with the same hyperparameters, you'll get different models that produce different values for the metric.  This causes it to get confused.  It correctly identifies that n_estimators=20 is the best value for the hyperparameter, since the lowest score obtained on any evaluation (0.012) is for that value.  But the score it reports for it is 0.029, the score from the second evaluation.  That is higher than the score for n_estimators=31 (0.024).

Is there actually a legitimate reason for the function to get evaluated twice with the same hyperparameters?  If not, that's a bug.  We should figure out why it's happening.  But if that is reasonable behavior, the simplest solution would be to have it immediately return the score it calculated before, rather than training and evaluating a new model.

**Comment by peastman** [comment]
I understand it a little better now.  Before pyGPGO starts the main optimization, it first evaluates the function for a few randomly chosen inputs.  Notice "init" at the start of the first three lines above.  It doesn't have any checks to make sure the random inputs are unique.  In this case, two of them just happen to be the same.  That isn't ideal, and it would probably work better if they added that check.  But still, it's within the documented behavior.  So I believe the right fix is for us to make sure we always return the same value for a given set of hyperparameters.  I'll get in a PR for that.
