### ISSUE TITLE
Command '['/root/miniconda/bin/conda', 'install', '--yes', 'python==3.7.12', 'pdbfixer', 'rdkit=2020.09.02', 'openmm']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by hjzhang1018** [deepchem/deepchem#2701]
## 📚 Installation

Just as normal, I ran this installation commands. But an error occurred. I used the following code as the same in tutorials.
```
!curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py
import conda_installer
conda_installer.install()
!/root/miniconda/bin/conda info -e
```

Error message:
---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
<ipython-input-6-402465323f4b> in <module>()
      1 get_ipython().system('curl -Lo conda_installer.py https://raw.githubusercontent.com/deepchem/deepchem/master/scripts/colab_install.py')
      2 import conda_installer
----> 3 conda_installer.install()
      4 get_ipython().system('/root/miniconda/bin/conda info -e')

1 frames
/usr/lib/python3.7/subprocess.py in check_call(*popenargs, **kwargs)
    361         if cmd is None:
    362             cmd = popenargs[0]
--> 363         raise CalledProcessError(retcode, cmd)
    364     return 0
    365 

CalledProcessError: Command '['/root/miniconda/bin/conda', 'install', '--yes', 'python==3.7.12', 'pdbfixer', 'rdkit=2020.09.02', 'openmm']' returned non-zero exit status 1.

## Checklist

- [x] I followed the [installation guide](https://deepchem.readthedocs.io/en/latest/get_started/installation.html).
- [x] I used Google Colab.
- [x] I do have multiple CUDA versions on my machine.

**Comment by arunppsg** [comment]
Try the following in colab:

```
!pip install --pre deepchem
!pip install rdkit-pypi
```

Related issue #2613

**Comment by hjzhang1018** [comment]
Thank you @arunppsg very much. Solved.

**Comment by Ferx2226** [comment]
Great, it worked perfect for me! :) Thank you so much

@arunppsg By any chance do you know how to import RDKit after applying those changes. When I use: 
import rdkit as chem

I got the next error: 

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-10-ee6f2a90aa70> in <module>()
      1 import torch
----> 2 import rdkit
      3 import rdkit.Chem as Chem
      4 from rdkit.Chem import rdFMCS
      5 from matplotlib import colors

**ModuleNotFoundError: No module named 'rdkit'**

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.

I'd appreciate your help :)

**Comment by arunppsg** [comment]
Here is a nice introduction to [rdkit](https://www.rdkit.org/docs/)
