### ISSUE TITLE
Swap Tensorflow install to use community conda site

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#275]
https://github.com/conda-forge/tensorflow-feedstock

Currently, the install directions point to a non-standard conda version. Better to point to the officially recommended conda channel.

**Comment by jekriske-lilly** [comment]
One of the issues is that the new version of tensorflow users a suffix of "index" instead of "ckpt" this causes any restore operation to fail.

**Comment by rbharath** [comment]
@jekriske-lilly Good point on the checkpoint format. Ran into this yesterday internally with our new Tensorflow 0.12 machine failing to load checkpoints of previously trained models (CC @joegomes). It looks like the new checkpoint version significantly reduces latency and memory, so we might just want to swap directly to the new version.

**Comment by joegomes** [comment]
@rbharath I've made a PR #313 with some updates to the TF model classes.  Not sure how we want to handle the write_version issue, my current implementation assumes write_version=2.  It seems like the `restore()` function can handle both v1 and v2, but the `_find_last_checkpoint()` function breaks due to the change in checkpoint naming convention.  It should be possible to support v2 by default and add a check in case the user is trying to load a v1 ckpt.  Any thoughts on how you want to do this?

**Comment by rbharath** [comment]
Since #313 has been merged, we've swapped to using the new Tensorflow pip install command in tests/directions. Going to go ahead and close.
