### ISSUE TITLE
Roadmap to port Keras layers to Torch

### ISSUE THREAD

**Issue by atreyamaj** [deepchem/deepchem#2930]
## 🚀 Feature

As planned, Deepchem will be shifting to more torch-based dependencies. As such, the first step in doing so is to port over the layers from Keras to Torch. This issue serves as a checklist for the most important layers (in the same order) to be ported over.

- [ ] GraphConv + pool
- [x]  AtomicConvoluton
- [ ] SetGather
- [ ] GraphEmbedPoolLayer
- [ ] GraphCNN
- [ ] WeaveLayer
- [ ] MessagePassing (MPNN)
- [ ] EdgeNetwork (MPNN)
- [x] GatedRecurrentUnit(MPNN)
- [x] InteratomicL2Distances
- [x] LSTMstep
- [ ] AttnLSTMEmbedding
- [x] ~SwitchedDropout~ (see discussion in issue linked below)
- [x] WeightedLinearCombo
- [x] CombineMeanStd
- [x] Neighborlist

I will be attempting to port over InteratomicL2Distances to start off. Contributions are welcome!

**Comment by airpods69** [comment]
What all models have been ported to torch here? (or is the list up to date)

**Comment by subzjee** [comment]
I ported `NeighborList` to PyTorch. The result of the test function for `NeighborList` for the Torch version is identical to the original result while it used TensorFlow. 
I also commented some unused variables and lines because of `flake8`.
[Link to branch](https://github.com/subzjee/deepchem/tree/neighbor-list-torch).

I had to remove `flake8` temporarily from the pre-commit in order to push it because `flake8` wanted to see a space after a comma in some unrelated code while `yapf` kept removing that same exact space.
Not sure how to deal with that. That was the only thing reported by `flake8`.

**Comment by subzjee** [comment]
I have been having a blast working on this. This caused me to get all excited and eager to continue working so I ported `SwitchedDropout`.
After finishing it, I realized that it only existed because of a limitation of Keras, which @peastman then also noted on the [PR](https://github.com/deepchem/deepchem/pull/3024).

While going through the list, I noticed that `GatedRecurrentUnit` is already [implemented](https://pytorch.org/docs/stable/generated/torch.nn.GRU.html) in PyTorch so that might not be needed as well.
It might be worth it to go through the list and see if there are others.

In the meantime, I've started working on `AtomicConvolution`.

**Comment by vinay-hebb** [comment]
Is it a good idea to compare outputs of PyTorch and Tensorflow as part of testing? Currently, we have tests separated for PyTorch and Tensorflow (not sure if this is intentional). Few tests are checking for output shape only. Comparing PyTorch and Tensorflow outputs can produce bug-free code.

**Comment by rbharath** [comment]
Yes that would be a great idea. The way we've done this before is ensuring the existing TF tests pass out of box for the PyTorch reimplementation

**Comment by rbharath** [comment]
Also #2863 is related to this list. Converting the remaining TF models to PyTorch may necessitate adding some new layers in as well

**Comment by vinay-hebb** [comment]
> Yes that would be a great idea. The way we've done this before is ensuring the existing TF tests pass out of box for the PyTorch reimplementation

Sure. I am planning to port LSTMStep as first step and then add tests which can compare Tensorflow and PyTorch

**Comment by soma2000-lang** [comment]
@rbharath working on GraphCNN

**Comment by riya-singh28** [comment]
I am working on porting EdgeNetwork (MPNN).

**Comment by GreatRSingh** [comment]
I am working on Porting SetGather.

**Comment by GreatRSingh** [comment]
I am working on Porting AttnLSTMEmbedding.
