### ISSUE TITLE
ValueError: y has more than n_class unique elements.

### ISSUE THREAD

**Issue by ccy5123** [deepchem/deepchem#2992]
## ❓ Questions & Help

```
dataset_file = 'PA summary.csv'
tasks = ['ApL(nm^2)', 'Thickness(nm)', 'K_a(Modulus)(mN/m)', 'Diffusion Coefficient(10^-8cm^2/s)']
featurizer_func = dc.feat.CircularFingerprint()

loader = dc.data.CSVLoader(feature_field = 'smiles', featurizer=featurizer_func, tasks = tasks, id_field = 'Compound ID')
dataset = loader.create_dataset(dataset_file)

transformer = dc.trans.BalancingTransformer(dataset=dataset)
dataset = transformer.transform(dataset)

model = dc.models.MultitaskClassifier(n_tasks=4, n_features=2048, layer_sizes = [1000])
model.fit(dataset, nb_epoch=10)
```

[PA summary.csv](https://github.com/deepchem/deepchem/files/9081942/PA.summary.csv)

I tried to apply my own data with Introduction to DeepChem Tutorial 10th. 
I think it seems to be a problem with 'width of a layer' or 'n_classes' argument of MultitaskClassifier, but how can I solve the problem?

**Comment by Suzukazole** [comment]
Hey, from a first glance it looks like the dataset that you have provided is meant for regression. For using the MultitaskClassifier the labels(y of the dataset) have to be segregated into classes. For example, in the tutorial that you cite, on examining the labels of the dataset you can see that there are two classes (i.e) whether the molecule is active or not (1 or 0). 
I trained a MultitaskRegressor instead of the classifier on the dataset that you have provided and it seems to fit the data.
