### ISSUE TITLE
run_benchmark.py calls benchmark_loading_datasets() with wrong argument name.

### ISSUE THREAD

**Issue by ktaneishi** [deepchem/deepchem#304]
python examples/run_benchmark.py tox21 tf 10

causes the next error;

Traceback (most recent call last):
  File "examples/run_benchmark.py", line 113, in <module>
    verbosity='high', out_path=out_path)
TypeError: benchmark_loading_datasets() got an unexpected keyword argument 'dataset_name'

argument name might be "dataset".

**Comment by rbharath** [comment]
@miaecle Would you mind taking a look?

**Comment by miaecle** [comment]
@ktaneishi Thanks for pointing out the error! This is due to the update of benchmark script, in which I also changed the argument name. I have initiated PR #305 to solve for this.

**Comment by miaecle** [comment]
@rbharath Thanks for the reminder! Also, are we still going to use run_all_benchmark anymore? I guess the current benchmark script can already fulfill this task. For the run_benchmark script, I prefer to keep it for it is mostly used in hyperparameter search, in which different hyperparameter sets are evaluated on the same dataset and model.

**Comment by rbharath** [comment]
@miaecle Good call. I think we can go ahead and remove `run_all_benchmark.py` since `benchmark.py` already handles this. Perhaps we should name `run_benchmark.py` to `benchmark_hyperparam_search.py` to match its intended purpose?

I'll go ahead and close this issue since the reported error has been fixed.
