### ISSUE TITLE
pcba dataset

### ISSUE THREAD

**Issue by mike1729** [deepchem/deepchem#351]
I have a question related to pcba dataset. There are some bio_assays which have substantially less compounds than in pubchem database. For example, in your file there are ~300k coumpounds for assay aid686978, but in pubchem there are ~400k compounds. Moreover, almost all missing compounds were inactive. Do you know why this is a case, and if yes, could you please explain why you cut them off?

**Comment by rbharath** [comment]
@mike1729 The PCBA datasets are the same dataset first presented in https://arxiv.org/abs/1502.02072. I believe that we filtered a number of the compounds that failed some basic sanity checks. If you have in-depth questions, I'd recommend reaching out to @skearnes who did the bulk of the processing work.

Going to go ahead and close this issue since it's not directly a deepchem issue. Feel free to reach out over email if you have further questions.
