### ISSUE TITLE
Training on missing values

### ISSUE THREAD

**Issue by CCXD** [deepchem/deepchem#367]
In the regression examples that I've seen, most compounds miss values for some of their tasks.
If I understood correctly from the code, these values are set to 0 eventually, then scaled together with the other y values, and fed into the model as if they were truly 0.
The resulting predictions of a model trained on a sparse dataset is that most predictions will be around 0, apart from the tasks that are well populated.

Is this an intentional design choice?
A solution could be to keep the missing labels as 0, and to grab the indices of the nonzero values when calculating the loss, and slicing the predicted tensor with those indices.

**Comment by rbharath** [comment]
This is a good question that's not well documented in code (need to add on
to #366). The missing values are indeed set to zero, however they don't
affect the learning since their example weights are also set to 0.
(DeepChem dataset objects have a `dataset.w` attribute that encodes per
example weights.) Since we set example weights to zero, we in-effect slice
out the missing values. (We can't actually remove data points since in
multitask datasets, an example may be missing readouts for some tasks but
not others).


On Jan 20, 2017 4:08 AM, "CCXD" <notifications@github.com> wrote:

In the regression examples that I've seen, most compounds miss values for
some of their tasks.
If I understood correctly from the code, these values are set to 0
eventually, then scaled together with the other y values, and fed into the
model as if they were truly 0.
The resulting predictions of a model trained on a sparse dataset is that
most predictions will be around 0, apart from the tasks that are well
populated.

Is this an intentional design choice?
A solution could be to keep the missing labels as 0, and to grab the
indices of the nonzero values when calculating the loss, and slicing the
predicted tensor with those indices.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/deepchem/deepchem/issues/367>, or mute the thread

**Comment by CCXD** [comment]
Thanks for the response, I was not aware of the fact that weights are set to 0.
This explains why the calculated metrics using an Evaluator was different from my own calculated metrics from the predictions that are exported. Maybe prediction exports should also take in account weights set to 0?

**Comment by rbharath** [comment]
This raises a good point, but may be better suited to adding to documentation or notes rather than changing the code itself. The current semantics of an `Evaluator` is that it runs the model on all examples in a `Dataset`, leaving it to the user to handle filtering. Maybe something for an FAQ or gotchas section though.

**Comment by CCXD** [comment]
Alright that makes sense, thanks.
