### ISSUE TITLE
passing in empty tasks to DataLoader fails

### ISSUE THREAD

**Issue by proteneer** [deepchem/deepchem#375]
When trying to validate truly blind prospective data, we often have csv files/datasets that have only the smiles column. So the natural procedure is to pass tasks=[] to the DataLoaders, which results in the following exception:

```
  File "/home/yutong/venv/lib/python3.5/site-packages/deepchem/data/data_loader.py", line 30, in convert_df_to_numpy
    np.reshape(np.array(df[task].values), (n_samples, 1)) for task in tasks])
  File "/home/yutong/venv/lib/python3.5/site-packages/numpy/core/shape_base.py", line 277, in hstack
    if arrs[0].ndim == 1:
IndexError: list index out of range
``

**Comment by rbharath** [comment]
Good find! Yes, this issue needs a fix. PR welcome here. There's a little bit of thinking to do since `convert_df_to_numpy` assumes that at least one task is present, but there's probably a reasonable workaround.

There's a back-log of large PRs right now (#365, #369, #374), so it might take us a week or two to come up with a solution from our end.

**Comment by proteneer** [comment]
Todo: add in support for NumpyDataset and other DataLoader classes.

**Comment by rbharath** [comment]
Going to go ahead and close this issue since #380 solved the main issue here.
