### ISSUE TITLE
BEDROC Metric

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#412]
The IRV paper (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2750043/) argues for the use of the Boltzmann-Enhanced Discrimination of the Receiver Operating Characteristic (BEDROC) metric instead of the usual ROC curve. The argument is that BEDROC is a better measure is a better measure of molecular activity prediction than ROC-AUC. It would be cool to get this merged into DeepChem metrics so we can add it to the benchmark suite.

CC @miaecle

**Comment by proteneer** [comment]
Chris Bayly's paper is probably the better canonical reference: https://www.ncbi.nlm.nih.gov/pubmed/17288412

**Comment by evanfeinberg** [comment]
from rdkit.ML.Scoring.Scoring import CalcBEDROC, CalcROC

bedroc_auc = CalcBEDROC(score_df.values, col=0, alpha=20)

where ```score_df``` has two columns

Is how I've been computing BEDROC in ```conformation```

**Comment by proteneer** [comment]
+1 - really useful.

**Comment by proteneer** [comment]
@evanfeinberg 

You're using an alpha of 20? From the paper - I think for BEDROC to be meaningful it should satisfy the condition that alpha*(ratio of actives to inactives) be significantly less than 1. That is, for something like tox21 where only about 3-5% of the dataset is active, the default choice of 20 seems inappropriate. Intuitively, the alpha parameter is a measure of desired enrichment, which is only meaningful if the ratio of actives to inactives is small. Furthermore, increasing alpha values tends to lead to an increase in the statistical error of the measurement method itself.

**Comment by proteneer** [comment]
Also be aware that it's totally nonsensical to compare BEDROCs across different alpha values, so we should document clearly what the chosen alphas are when reporting results.

**Comment by evanfeinberg** [comment]
Thanks for the insights! Using alpha of 20 for a completely different
dataset and paper but your comments are spot on for the specific use-case
of Tox21 (with which I am only tangentially involved)

**Comment by agitter** [comment]
Jumping in here with a marginally related comment after I asked about the historical reasons for using ROC in this domain.

In genomics, ROC has fallen out of favor due to class imbalance.  A recent benchmarking paper compared the relative performance of different DNase footprinting methods by looking at multiple evaluation metrics, including area under ROC curves at different cutoffs.
http://www.nature.com/nmeth/journal/v13/n4/fig_tab/nmeth.3772_F4.html

The figure is busy, but I found it useful to see how relative performance changes across different metrics, e.g. perhaps across different alpha values for BEDROC in this context.

**Comment by rbharath** [comment]
I like the idea of adding [AUPR](http://stats.stackexchange.com/questions/99916/interpretation-of-the-area-under-the-pr-curve) to MoleculeNet since it's a parameter free method like ROC-AUC. 

One issue I have with the 100%/10%/1% FPR cutoffs for evaluation is that it makes things harder for ML people who aren't chemistry experts. While ROC-AUC and AUPR can be dealt with in a black box fashion, methods developers would have to really dig into a dataset to figure out which FPR makes sense for that application.

CC @jisraeli: Would love to hear your thoughts on this thread and your lab's experience with the TF-binding data challenge.

**Comment by jisraeli** [comment]
@rbharath: Let me start with a huge congrats to you and the team here on putting together MoleculeNet - quality benchmark datasets are invaluable for machine learning in this field.

Equally important are evaluation metrics that reflect what downstream practitioners would want out of the predictions. The field of TF binding imputation has had a clear gap in this regard for quite some time. Below I provide a brief overview of the task at hand, key developments over the past 2 years, and the [ENCODE-DREAM TF binding challenge](https://www.synapse.org/#!Synapse:syn6131484/wiki/402026) in that context:

The human genome has 3E9 bp, processed ChIP-seq data puts the number of reproducible TF sites genome-wide in the ~1K-50K range (varies by TF and celltype), and this data allows TF site detection with ~200 bp resolution: The positive class in these tasks is usually <0.1%. TF site predictions may be used for targeted validation experiments and other downstream models (of gene expression for example). For the purposes of experimental validation, the predictions have to control the false discovery rate (FDR) - a typical FDR experimentalists ask for is 10%. For downstream models, low FDR for TF binding predictions is not as critical as along as those downstream models meet their own FDR requirements - an FDR of 50% in this context could work just fine.

Without these application-specific metrics in mind, a brief survey of recent literature may suggest TF binding is nearly solved. [DeepBind](http://www.nature.com/nbt/journal/v33/n8/full/nbt.3300.html) reported SOTA auROC on the previous DREAM TF binding challenge, and follow-ups to DeepBind such as [Deep Motif](https://arxiv.org/abs/1605.01133) and [Genetic Architect](https://arxiv.org/abs/1605.07156)  further improve auROC on DeepBind's tasks to 0.95. However, the evaluation of these models is not a good indicator because it is based on 1) a synthetic negative set orders of magnitude smaller than the full human genome, 2) auROC and 3) same test celltype as training celltype. [DeepSEA](http://www.nature.com/nmeth/journal/v12/n10/full/nmeth.3547.html#methods) and followups such as [DanQ](https://academic.oup.com/nar/article/44/11/e107/2468300/DanQ-a-hybrid-convolutional-and-recurrent-deep) report SOTA auROC and auPRC on 17% of the genome on same celltype predictions - this evaluation improves one the first two issues. A [recently published deep learning model](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005403) seems to beat both DeepBind and DeepSEA on their respectively test data, but when its evaluated on a full test chromosome (not negative set subsampling as usually done) the sobering truth comes out: its recall is <10% at 50% FDR for most tasks - 10% FDR is not reported most likely because the recall there is effectively 0%. Based on my own evaluation, it is not unusual to get >0.99 auROC and still get 0% recall at 10% FDR.

The TF binding challenge asks for predictions on an unseen celltype, on unseen chromosomes, on every interval (no negative set subsampling). Participants are ranked by combining their auROC, auPRC, recall at 10% FDR, and recall at 50% FDR (see the challenge wiki for more details on this). We also show their recall at 5% and 25% FDR but do not use those for ranking. I am not familiar enough with this domain to suggest specific metrics at the moment, but I'd be happy to discuss these questions in more detail and help converge on them. By sharing the developments in the TF binding field, I hope that I have clarified the importance of establishing clear evaluation metrics early on.

**Comment by jisraeli** [comment]
I looked at the figure @agitter pointed to from the overview of footprinting-based methods for TF binding predictions. It suggests the HINT method comes out at the top with an auPRC of ~0.7. HINT participated in the challenge so you can see how well it works - while performance is commendable, it's a long way from auPRC of ~0.7. There are multiple submissions that outperformed HINT, and an auPRC of 0.7 would be a serious breakthrough wrt to the top submissions.

The FPR-based metrics in this case do not really correspond to the needs of downstream applications. When the negative set is 99.9% of the data, if we assume 100% recall for FPR of 1%, that means that for every 10 true positive detected you get 100 false positives or, equivalently, a 91% FDR. It doesn't make sense to validate predictions >91% of which are not going to work.

**Comment by agitter** [comment]
@jisraeli I didn't want to read too much into the conclusions of that benchmarking study, I was mostly referring to it for the visualization and presentation of the results.  I accept your conclusions about HINT.  My main point was that I find it useful when multiple evaluation metrics or thresholds are used in a benchmarking study, even if one of them is given priority.

I see your point about how auROC is still inappropriate at more stringent FPR cutoffs for TF binding.  In the DREAM example, I agree that recall at a fixed FDR is a good evaluation metric.  It still makes sense to look at multiple thresholds (e.g. 10% and 50%) depending on whether the predictions are being used for experimental validation or downstream modeling.

In MoleculeNet, @rbharath and others can say more about what the right metric is.  My main suggestion was to consider more than one metric or threshold, perhaps with a visualization as used in the Gusmao study I linked.  I expect that for MoleculeNet, an experimentalist and an machine learning researcher will have different needs and different preferred metrics.

**Comment by rbharath** [comment]
This is a great discussion. Thanks for the feedback @agitter and @jisraeli. Here's my current take on things we should do.

- Add AuPRC as a MoleculeNet metric.
- Add 10% FDR, 25% FDR and 50% FDR, but only as secondary metrics in appendices. The information should be there for experts who want to really dig into the datasets, but I'd like to emphasize simplicity for ML people who just want to optimize a single metric.

CC @miaecle

**Comment by agitter** [comment]
@rbharath thanks for adding PRC in the latest MoleculeNet paper.  It looks like that was just one of a huge number of improvements in this version.

**Comment by rbharath** [comment]
@miaecle did the heavy lifting, so props go to him!

**Comment by rbharath** [comment]
The original feature request called for adding in the BEDROC metric. Although we ended up adding in PRC into DeepChem, it would still be a good contribution to add in BEDROC to `dc.metrics`.

This implementation should be relatively brief (< 50 lines at first guess) so would be a good first contribution. If you'd like to take it on, please leave a comment here and raise a PR marked [WIP] tracking your implementation.
