### ISSUE TITLE
Generic TensorGraph Support In Deepchem Models

### ISSUE THREAD

**Issue by lilleswing** [deepchem/deepchem#471]
Sequential Model Doesn't have enough power to do splits and recombines.  Create a new Model implementation that allows for generic graph structures.

**Comment by lilleswing** [comment]
It would be nice when loading the model to be able to get layers by name, and view the graph as an image or flow chart.

**Comment by rbharath** [comment]
Definitely agree with the need for a generic Graph model. @lilleswing and I chatted about this offline. Idea might be to have 

`graph_model.add_layer(layer, [parent_1,...,parent_n])`

Might use `networkx` to store graph of layers. As a note, I'd vote against keeping graph visualization in the core library (since we can't write unit tests). Maybe belongs in utils or an IPython notebook?

**Comment by lilleswing** [comment]
RFC pull request here
https://github.com/deepchem/deepchem/pull/473

**Comment by peastman** [comment]
Is this intended to replace `SequentialGraph`, or do we plan to maintain two different Keras-like modular APIs?

**Comment by rbharath** [comment]
We discussed offline, but to document, the idea is to that `TensorGraph` be the parent superclass for all other DeepChem classes. So `SequentialGraph` would inherit from `TensorGraph` once refactored.

**Comment by rbharath** [comment]
Now that #493 has been merged in, the major TODO is converting the models in DeepChem over to `TensorGraph`. Here is the current accounting for who's doing what:

- @lilleswing: Graph Convolutions
- @peastman: Fully Connected Multitask Networks
- @miaecle: DTNNs and DAGs

As a soft guideline, let's try to use `TensorGraph` for all new models (this will be bent of course, because research is often easiest to do in pure Tensorflow once you're comfortable with it).

**Comment by rbharath** [comment]
Going to close since I think these TODOs have been hit.
