### ISSUE TITLE
Sluice Network Implementation

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#573]
Sluice Networks look like an interesting concept for improving multitask learning. Could be a nice method to improve the performance of multitask learning, especially on larger datasets.

https://arxiv.org/abs/1705.08142

It would be very cool to get a sluice network implementation in DeepChem. PRs for this purpose welcome.

**Comment by peastman** [comment]
I'm skeptical about it.  A lot of what they're doing looks very suspicious.

They start by multiplying the size of their network by the number of tasks.  So they have a huge network, way bigger than it needs to be with way more capacity than it needs.  Then they try to compensate for that by arbitrarily chopping it into pieces, and adding variables that let it turn off large blocks of connections all at once.  Of course, a simple dense network could do exactly the same thing by turning off each connection individually.  Having one variable that does that all at once might be easier to learn, but that's only an issue because their network is way too large to begin with.

**Comment by lilleswing** [comment]
@peastman I just did a deep dive into the paper and agree that it is an explosion in network size.  
When discussing complexity in the paper they compare it to M single task networks.  Compared to M single task networks it takes

``` bash
S^2 * K * M^2 + K * M
# S = subspaces, generally 2
# K = number of layers
# M = Number of tasks
```
more training variables.

Their case study was on NLP which has way more training data then we are dealing with generally

![selection_006](https://user-images.githubusercontent.com/1225605/26837767-4692720c-4aac-11e7-9482-475c9c26b5ed.png)

I question if this technique will be useful in the low-data world we are dealing with.

**Comment by rbharath** [comment]
Good points here. Going to go ahead and close this issue for now.
