### ISSUE TITLE
TensorGraph Example (test_mnist.py) may have minor bug

### ISSUE THREAD

**Issue by alphaCTzo7G** [deepchem/deepchem#612]
I was working through the test_mnist.py, and noticed that its trying to import the Conv2d class on line 12, with the d in Conv2d in small caps.

`from deepchem.models.tensorgraph.layers import Reshape, Flatten, Feature, Conv2d, MaxPool, `Label

But layers.py has this in line 736

`class Conv2D*`

with 2D in big caps

Perhaps the test_mnist.py (https://github.com/deepchem/deepchem/blame/master/examples/tensorgraph/test_mnist.py) file under needs to be update to import Conv2**D**.

**Comment by dibyadeeppaul** [comment]
Have only been looking at this example file today.. so maybe I dont understand everything.

Couple of other things I noticed.. maybe why the tutorial/example is not running

The code in the ipynb and the py file is quite different.. Is this intentional?

In the ipynb file
1. there is a call to a add_feature function, as well as in a lot of places (https://github.com/deepchem/deepchem/search?utf8=%E2%9C%93&q=*add_feature&type=). However I dont see it defined?

2. In cell [5], tg = dc.models.TensorGraph(tensorboard=True, model_dir='/tmp/mnist') should probably be replaced with tg = dc.models.tensorgraph.tensor_graph.TensorGraph(tensorboard=True, model_dir='/tmp/mnist')?

**Comment by rbharath** [comment]
@dibyadeeppaul Thanks for the bug report. Should probably be `Conv2D`.

I believe the ipynb's are out of date and possibly broken. PRs fixing them welcome!

**Comment by dibyadeeppaul** [comment]
Will work on it!

**Comment by rbharath** [comment]
I believe the file in question has now been removed and been superseded by the ipython notebook tutorial. Going to close this issue.
