### ISSUE TITLE
What is _get_tf doing?

### ISSUE THREAD

**Issue by mostafachatillon** [deepchem/deepchem#708]
I have a question for @lilleswing, it's not an issue.

I want to remove the line:
   ` with cnn._get_tf("Graph").as_default():`

in my code, because I want to use the default graph.

I replace train_op with:
    `global_step_var = tf.Variable(0, trainable=False)`
    `train_op =tf.train.AdamOptimizer().minimize(cnn.loss.out_tensor, global_step= global_step_var)`

But then I receive the error:

`> 301  train_op =tf.train.AdamOptimizer().minimize(cnn.loss.out_tensor, global_step= global_step_var)`
    `302  sess=tf.Session()`

`/home/mostafa/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in minimize(self, loss, global_step, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, name, grad_loss)
    313         aggregation_method=aggregation_method,
    314         colocate_gradients_with_ops=colocate_gradients_with_ops,
--> 315         grad_loss=grad_loss)
    316 
    317     vars_with_grad = [v for g, v in grads_and_vars if g is not None]

/home/mostafa/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/optimizer.pyc in compute_gradients(self, loss, var_list, gate_gradients, aggregation_method, colocate_gradients_with_ops, grad_loss)
    378     processors = [_get_processor(v) for v in var_list]
    379     if not var_list:
--> 380       raise ValueError("No variables to optimize.")
    381     var_refs = [p.target() for p in processors]
    382     grads = gradients.gradients(`

`ValueError: No variables to optimize.`

I look at line 542 of the definition of _get_tf(self, obj) and I find: 

    TODO(LESWING) REALLY NEED TO DOCUMENT THIS

@lilleswing can you explain why _get_tf is necessary, and how to do without it?

**Comment by lilleswing** [comment]
Sorry I didn't see this, but it was only open for one day on a Sunday.

You can pass the TensorFlow Graph into the Contructor of Tensorgraph to use whatever graph you want.
https://github.com/deepchem/deepchem/blob/master/deepchem/models/tensorgraph/tensor_graph.py#L27

The reason we have _get_tf is so that TensorGraph is persistable.  Tensor Objects are not picklable -- and we scope un-pickable objects that we recreate on load in the TensorGraph#tensor_objects variable and then lazily create them by calling TensorGraph._get_tf.

Also for your Generator/Discriminator work you can look through our Base GAN class to use our "Submodels"

**Comment by rbharath** [comment]
https://github.com/deepchem/deepchem/issues/1014 proposes extra documentation to address this issue.
