### ISSUE TITLE
TensorGraph Memory issues

### ISSUE THREAD

**Issue by sharma409** [deepchem/deepchem#743]
It seems that tensorgraph has an automatic saver which saves the model via pickling, and as a result I am exceeding the memory limit on machines and my jobs are crashing. This usually happens while restoring parameters from model (as indicated by "Restoring parameters from /tmp/net/model-(######)" message)

How can i turn off this functionality for tensorgraph models? I have attempted to set the checkpoint interval very high and set max_check_points_to_keep to 1, but that hasn't solved the memory issue [by running tg.fit(train, nb_epoch=self.nb_epoch, checkpoint_interval=10e10, max_checkpoints_to_keep=1) ]

How should I prevent the model from being saved and taking up too much memory?

**Comment by rbharath** [comment]
When you instantiate the `TensorGraph` object, try setting `checkpoint_interval=100000` and `max_checkpoints_to_keep=1`

**Comment by Moooooooon** [comment]
>  Can you try setting model_dir explicitly to see what's being written to disk?

It works very well.
I had the same problem when I tried 1000 times to find the parameters of the model.

Despite your option(`max_checkpoints_to_keep=1`), many models are created because deepchem tries to store every model which is declared. 
In other words, the save file is created as many times as the model is created.
The core of the problem is a lot of check_point_directories, Not check_points_files.
_______
 As @rbharath mentioned, explicitly setting `model_dir` is quick and simple solution.

To explain in more detail, you can specify `logdir ` parameter when declaring a `model`.
For example, 
`model = dc.models.TensorflowMultiTaskRegressor( logdir= EXPLICIT_PATH , ...) `

This setting continues to **overwrite** the saved model.
As a result, you have only one saved model, assuming that the batch number is the same.
Good luck!

**Comment by rbharath** [comment]
Good analysis @Moooooooon. @sharma409 I believe you're constructing many models. Since each model is placed in a new directory, even if only one checkpoint is saved, if 100 models are constructed, that's 100 checkpoints which will cause issues. Setting everything to share an explict `model_dir` should avoid this overhead.

**Comment by sharma409** [comment]
Yep, this fix seems to have worked. Thanks!
