### ISSUE TITLE
AlphaGo Zero

### ISSUE THREAD

**Issue by rbharath** [deepchem/deepchem#890]
The new AlphaGo Zero algorithm encapsulates MCTS as a powerful policy search amplifier. While this may not be directly relevant (yet) to any of our applications, it might be interesting to implement a version in DeepChem if we can.

CC @peastman, who made some very insightful comments about AlphaGo Zero offline

**Comment by peastman** [comment]
Already working on it. 😀

**Comment by peastman** [comment]
By the way, why do they call it "Monte Carlo tree search"?  It's a totally deterministic search, *not* a MC search!  I guess because they have a non-deterministic environment.  You don't know how the other player will respond to your moves.  But the way they pick the moves for the search doesn't involve any randomness.  That makes it a misleading name.

**Comment by peastman** [comment]
As I work on this, I'll post here to describe things I'm changing relative to what's in the paper, and the reasons why.  So far I've been working on the tree search, so I'll start with that.  They make several assumptions that are true for Go, but false for many other problems:

- There are no intermediate rewards.  The total reward for an episode is entirely determined by the final step.
- That total reward is either 1 or -1.
- Discounting rewards is not appropriate.
- Episodes are short.  No game of Go lasts more than a few hundred moves, so the tree search can follow every episode to the very end to see what the final reward is.
- On the other hand, they use an optimization that's very specific to Go: when they decide the odds of winning are sufficiently low, they end that episode immediately and assume the final reward will be -1.  Effectively they're assuming that in certain cases, they can predict with high accuracy what the total reward for the rest of the episode will be.  That's not true in general.

To make this into a more general algorithm, I'm changing the tree search a bit.  I ask the user to specify a maximum search depth.  The tree search stops whenever an episode gets more than a fixed number of steps beyond the current root without it terminating.  In that case, I use the network's value function to estimate the total reward beyond that point.  I also allow the user to specify a discount factor.  You can, of course, set it to 1.0 if you don't want discounted rewards.

This has a consequence for one other aspect of the tree search.  When starting a new search, they reuse any data from the previous search that happened to pick the correct first step.  For some subset of the episodes from the previous search, the first move will have been the move we actually ended up taking.  Since it followed those episodes all the way to the end, they know exactly how they turned out and can keep the data from them.

We can still do that, but now it involves an approximation since those episodes are too short.  Suppose you set `max_search_depth=100`.  That means we'll run out a bunch of episodes for 100 steps.  But we'll also throw in a smaller number of episodes from the previous search, and those only went for 99 steps (relative to our new root).  And there's an even smaller number from the search before that, whose depth is only 98 steps.  And so on.

I don't think this is likely to be a problem.  I expect reusing that data to still give a net gain in accuracy.  It's just something to be aware of.

**Comment by patrickhop** [comment]
would love to see this code @peastman

**Comment by LRParser** [comment]
👍

**Comment by peastman** [comment]
The paper is a bit vague about how they balance the two tasks of self play to generate data, and training the network based on that data.  As far as I can tell, they do both tasks in parallel, but they don't indicate how much training they do per unit of data, or how much data they generate before passing that data off to the optimizer.  They do mention that each training batch consists of randomly chosen states from the 500,000 most recent games.  That's a huge replay buffer, but of course they're working on a pretty large scale (64 GPUs and 19 parameter servers).

Anyway, here's what I'm trying initially.  I do a strict alternation of generating data and then training on the data that was just generated.  The user can specify the number of steps to take in each iteration (that is, the number of data points that will be generated), the number of epochs of optimization to run with them, and the total number of iterations (generate data, optimize based on it) to do.

**Comment by peastman** [comment]
One part I'm a bit unsure how to handle is the constant `c_puct` that appears in their expression for choosing actions (see p. 361 top right).  They don't say what value they use for it or give any guidelines for how to pick a value.  They do cite a paper for the PUCT algorithm, but I looked it up and found the paper is actually about a different algorithm called PUCB which doesn't match what they're doing and has no corresponding constant in it!  I managed to find a different paper that does describe an algorithm called PUCT, but that one doesn't match what they're doing either, and also has no corresponding constant.  Sigh.

So, I could just ignore the whole issue, leave it as an arbitrary constant, and require the user to somehow come up with a value for it.  That's not going to be very helpful, though.  It's clear the magnitude of the constant should be proportional to the magnitude of rewards given by the environment, so I could try to automatically scale it in some way based on that.  It would be nice if the paper were a bit more informative, though.

**Comment by peastman** [comment]
Since we now have a working implementation of this, I've started experimenting with it on a real problem.  My conclusion is that it's a crazy expensive algorithm.  It may be a very robust method with good convergence properties, but don't even think about using it unless you have really serious amounts of computing power to devote to it.  There are good reasons they ran it on 64 GPUs and 19 parameter servers.

It comes down to the tree search.  The number of episodes you compute for each search must be large compared to the number of possible actions—that's essential for the PUCT algorithm.  In their case, it was 1600.  The number of steps in each episode must be enough to have a reasonable chance of it receiving a reward.  In their case, they ran every game out to the end, except when they were pretty confident it was going to lose, in which case it would resign early.  So the average episode length was probably somewhere around 100 steps.

So every tree search involved computing around 160,000 steps.  All of that just to take *one step* of the actual game.  They say all of that took about 0.4 seconds, which comes out to about 2.5 microseconds per step.  It's pretty clear they must have implemented most of this on the GPU and had it compute all 1600 episodes in parallel.

Now consider this statement from the paper describing how they did optimization.

> Each mini­batch of data is sampled uniformly at random from all positions of the most recent 500,000 games of self­-play.

So it had to play 500,000 games (tens of millions of steps) before they even performed their first step of optimization!

**Comment by peastman** [comment]
I hit "comment" before I meant to.  Anyway, my conclusion is that any Python implementation of this algorithm with an environment written in Python is probably going to be too slow to use for anything except toy problems.  Maybe if your environment has a very small number of actions, so you can get away with many fewer episodes for the tree search?  But if you want to apply this to any complicated problem, you need to have an environment with a *very* fast `step()` function, and also very large scale parallelization.

**Comment by rbharath** [comment]
@peastman's superb summary sums up this issue well. Going to go ahead and close.

**Comment by BIGBALLON** [comment]
@peastman 
Hello, peastman.

> They do cite a paper for the PUCT algorithm, but I looked it up and found the paper is actually about a different algorithm called PUCB which doesn't match what they're doing and has no corresponding constant in it! I managed to find a different paper that does describe an algorithm called PUCT, but that one doesn't match what they're doing either, and also has no corresponding constant. Sigh.

So, I could just ignore the whole issue, leave it as an arbitrary constant, and require the user to somehow come up with a value for it. That's not going to be very helpful, though. It's clear the magnitude of the constant should be proportional to the magnitude of rewards given by the environment, so I could try to automatically scale it in some way based on that. It would be nice if the paper were a bit more informative, though.

You are right, the paper cited by AlphaGo Zero proposed a algorithm called **PUCB (“Predictor +UCB”)**, the P means Predictor(which is reasonable in both old paper and AGZ paper), they modify the PUCB then use it in Tree, which called PUCT, so I think PUCB is proposed by the cited paper, but  PUCT is proposed by AGZ, so you can't find the constant ``c_puct`` in the old paper.
